import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import GifProvider from "@/context/gif.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GIPHY",
  description: "Generated by Nitish Singh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}className="bg-neutral-950 text-white min-h-screen`}
      >
        <GifProvider>
          <div className="container px-6 py-4 mx-auto">
            <Header />
            <main>{children}</main>
          </div>
        </GifProvider>
      </body>
    </html>
  );
}
